C#/Unity SDK Testsuite
clockworklabs/SpacetimeDBCircleGame pull request #3
Opened 2024-10-30 21:32 UTC by jdetter

## Description

We're moving the Unity code from the C#/Unity testsuite here to prevent duplication of the circle game project.

2024-10-30 21:43 UTC, jdetter commented on client/Assets/Scripts/GameManager.cs
> +        PlayerPrefs.DeleteAll();
```suggestion
```

2024-10-31 11:01 UTC, cloutiertyler commented on client/.gitignore
Amen.

2024-10-31 11:10 UTC, cloutiertyler commented on client/Packages/manifest.json
> +    "com.clockworklabs.spacetimedbsdk": "file:/Users/boppy/clockwork/com.clockworklabs.spacetimedbsdk",
I'm assuming you didn't mean to have this?

2024-10-31 11:10 UTC, cloutiertyler commented on server/Cargo.toml
> +spacetimedb = { path = "../../SpacetimeDB/crates/bindings" }
Same here.

2024-10-31 11:11 UTC, cloutiertyler requested changes
Left two comments.

2024-12-12 17:08 UTC, cloutiertyler approved these changes
This now LGTM

2024-12-12 17:08 UTC, merged